path:
    assembly_path : '/cluster/work/genome/Assemblies'
    output_path   : '/cluster/work/STR'
    
tools:
    bedtools: 'module load bedtools2/2.30.0 '
    trf:      '/cluster/work/tools/TRF/src/trf '
    fix_trf: '/cluster/work/Ref_STR/fix_trf_output.py'

assemblies :  ['ARS_UCD1.2','xxxx_hifiasmv152']

## please download tandem repeat finder and change all the path to your own dir or tools path
