resources:
  samples: 'your path/My_Selected_ids' ## sample id of bam file
  raw: 'your path/Raw_reads/'
  assembly: 'your path/ARS_UCD1.2/ARS_UCD.fasta'
  vcf: 'your path/sample_wise_vcf/'
  genomeDir: 'your path/UCD1.2/ensembl_104/genome_STAR/'
  sjdbFile: 'your path/genome_STAR/Bos_taurus.ARS-UCD1.2.104.chr.gtf' 

tools:
  multiqc: "your path/software/miniconda3/bin/multiqc"
  fastp: 'yourpath/fastp'
  samtools: 'yourpath//samtools'
  fastq_splitter: 'yourpath/gdc-fastq-splitter'
  sambamba: 'yourpath/sambamba_v0.6.6'
  load_picard_tools: "module load picard/2.25.7 \n"
  load_java_jdk: "module load jdk \n"
  load_r: "module load r/3.5.1 \n"
  picard_tools: 'java -jar yourpath/picard.jar'

fold_out:
  fastp: 'your path/fastp_out/'
  split_fastq: your path/split_fastq/'
  Alignment: 'your path/star_wasp/'
  sorted_alignment: 'your path//sorted_alignment/'
  dedup_alignment: 'your path//dedup_alignment/'
  metrics: 'your path/metrics/' 
  wasp_out: 'your path/wasp_filter/'  ## replace all path with your own.
